services:
  - type: web
    name: krutik-cyber-expert-discord-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_hosting_webservice_env.py

    envVars:
      - key: DISCORD_TOKEN
        sync: false

      - key: OWNER_ID
        value: "1378993981769252966"
